name: Deploy Bellarti App Dist Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Habilitar Corepack
      - name: Enable Corepack
        run: corepack enable

      # Limpiar cache de node
      - name: Clear npm cache
        run: npm cache clean --force

      # Desactivar todas las advertencias
      - name: Suppress Experimental Warnings
        run: export NODE_NO_WARNINGS=1

      # Remueve archivo problematico
      - name: Remove existing pnpm file
        run: rm -f /opt/hostedtoolcache/node/18.20.7/x64/bin/pnpm

      # Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm --force

      # Verificar instalación de pnpm
      - name: Verify pnpm installation
        run: pnpm --version

      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # Configurar variables de entorno
      - name: Configure environment variables
        env:
          VITE_API_BASE_URL: "https://api.bellarti.art/"
          VITE_WS: "wss://api.bellarti.art/ws"
        run: |
          echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> $GITHUB_ENV
          echo "VITE_WS=$VITE_WS" >> $GITHUB_ENV

      # Construir la aplicación
      - name: Build Vue.js application
        run: pnpm run build

      # Subir carpeta 'dist' al servidor
      - name: Desplegar en AWS Lightsail
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: "dist"
          target: "~/temp_dist"

      - name: Mover archivos a la carpeta de despliegue
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            sudo rm -rf /var/www/bellarti-app/*
            sudo mv ~/temp_dist/dist/* /var/www/bellarti-app/
            sudo rm -rf ~/temp_dist
            sudo systemctl reload nginx
            sudo systemctl restart nginx
