name: Deploy Bellarti App Dist Folder

on:
  push:
    branches:
      - main  # Desencadenar acciones solo en el branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Puedes cambiarlo si tu proyecto requiere otra versión
          cache: 'pnpm'

      # Paso 2: Instalar pnpm
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Paso 3: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # Paso 5: Construir la aplicación
      - name: Build Vue.js application
        run: pnpm run build

      # Paso 6: Subir carpeta 'dist' al servidor
      - name: Deploy dist folder
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz
          path: ./dist/
          remote_path: /home/ubuntu/dist/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
