name: Deploy Bellarti App Dist Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Habilitar Corepack
      - name: Enable Corepack
        run: corepack enable

      # Limpiar cache de node
      - name: Clear npm cache
        run: npm cache clean --force

      # Desactivar todas las advertencias
      - name: Suppress Experimental Warnings
        run: export NODE_NO_WARNINGS=1

      # Remueve archivo problematico
      - name: Remove existing pnpm file
        run: rm -f /opt/hostedtoolcache/node/18.20.7/x64/bin/pnpm

      # Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm --force

      # Verificar instalación de pnpm
      - name: Verify pnpm installation
        run: pnpm --version

      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # Configurar variables de entorno
      - name: Configure environment variables
        env:
          VITE_API_BASE_URL: "https://api.bellarti.art/"
        run: |
          echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> $GITHUB_ENV

      # Construir la aplicación
      - name: Build Vue.js application
        run: pnpm run build

      # Subir carpeta 'dist' al servidor
      - name: Deploy dist folder
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz
          path: ./dist/
          remote_path: /var/www/bellarti-app/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
