name: Deploy Bellarti App Dist Folder

on:
  push:
    branches:
      - main  # Desencadenar acciones solo en el branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar Node.js (versión 23)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Aquí se especifica la versión de Node.js

      # Paso 2: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          npm install

      # Paso 4: Construir la aplicación
      - name: Build Vue.js application
        run: |
          npm cache clean --force && npm install

      # Paso 5: Subir carpeta 'dist' al servidor
      - name: Deploy dist folder
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz
          path: ./dist/
          remote_path: /home/ubuntu/dist/
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
